<?php
declare(strict_types=1);
namespace App\Recruit\Transport\Controller\Api\V1\CoverPage;
use App\Recruit\Domain\Entity\CoverPage;use App\Recruit\Domain\Entity\Template;use App\Recruit\Infrastructure\Repository\CoverPageRepository;use App\Recruit\Infrastructure\Repository\TemplateRepository;use App\User\Domain\Entity\User;use Ramsey\Uuid\Uuid;use Symfony\Component\HttpFoundation\JsonResponse;use Symfony\Component\HttpFoundation\Request;use Symfony\Component\HttpKernel\Attribute\AsController;use Symfony\Component\HttpKernel\Exception\HttpException;use Symfony\Component\Routing\Attribute\Route;use Symfony\Component\Security\Core\Authorization\Voter\AuthenticatedVoter;use Symfony\Component\Security\Http\Attribute\IsGranted;
#[AsController] #[IsGranted(AuthenticatedVoter::IS_AUTHENTICATED_FULLY)] final readonly class MyCoverPageController { public function __construct(private CoverPageRepository $repo, private TemplateRepository $templates){}
#[Route(path:'/v1/recruit/private/me/cover-pages',methods:[Request::METHOD_GET])] public function list(User $loggedInUser): JsonResponse { $rows=$this->repo->findBy(['owner'=>$loggedInUser],['createdAt'=>'DESC']); return new JsonResponse(array_map($this->n(...),$rows)); }
#[Route(path:'/v1/recruit/private/me/cover-pages',methods:[Request::METHOD_POST])] public function create(Request $request, User $loggedInUser): JsonResponse { $p=$request->toArray(); $e=(new CoverPage())->setOwner($loggedInUser)->setFullName($p['fullName']??null)->setRole($p['role']??null)->setPhoto($p['photo']??null)->setDescription($p['description']??null)->setEmail($p['email']??null)->setPhone($p['phone']??null)->setHeader($p['header']??'About Me')->setProfile($p['profile']??null)->setSignature($p['signature']??null); $this->applyTemplate($e,$p['templateId']??null); $this->repo->save($e); return new JsonResponse($this->n($e),201); }
#[Route(path:'/v1/recruit/private/me/cover-pages/{id}',methods:[Request::METHOD_PATCH])] public function patch(string $id, Request $request, User $loggedInUser): JsonResponse { if(!Uuid::isValid($id)) throw new HttpException(400,'Invalid id'); $e=$this->repo->find($id); if(!$e instanceof CoverPage) throw new HttpException(404,'Not found'); if($e->getOwner()->getId()!==$loggedInUser->getId()) throw new HttpException(403,'Forbidden'); $p=$request->toArray(); foreach(['fullName','role','photo','description','email','phone','header','profile','signature'] as $f){ if(array_key_exists($f,$p)){ $m='set'.ucfirst($f); $e->$m($p[$f]); } } if(array_key_exists('templateId',$p)){ $this->applyTemplate($e,$p['templateId']); } $this->repo->save($e); return new JsonResponse($this->n($e)); }
#[Route(path:'/v1/recruit/private/me/cover-pages/{id}',methods:[Request::METHOD_DELETE])] public function delete(string $id, User $loggedInUser): JsonResponse { $e=$this->repo->find($id); if(!$e instanceof CoverPage) throw new HttpException(404,'Not found'); if($e->getOwner()->getId()!==$loggedInUser->getId()) throw new HttpException(403,'Forbidden'); $this->repo->remove($e); return new JsonResponse(null,204);} private function applyTemplate(CoverPage $e,mixed $id): void { if($id===null){$e->setTemplate(null);return;} $t=$this->templates->find((string)$id); if(!$t instanceof Template || $t->getType()!=='cover_page') throw new HttpException(400,'Invalid template'); $e->setTemplate($t);} private function n(CoverPage $e): array{return ['id'=>$e->getId(),'templateId'=>$e->getTemplate()?->getId(),'fullName'=>$e->getFullName(),'role'=>$e->getRole(),'photo'=>$e->getPhoto(),'description'=>$e->getDescription(),'email'=>$e->getEmail(),'phone'=>$e->getPhone(),'header'=>$e->getHeader(),'profile'=>$e->getProfile(),'signature'=>$e->getSignature()];}}
